services:
  app:
    image: gensound
    build: .
    container_name: gensoundapp
    volumes:
      - .:/usr/src/app
      - ./audio:/audio
      - ./output:/usr/src/app/output
    command: /bin/sh -c "while sleep 1000; do :; done"
    tty: true
