version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - ./shared:/usr/src/app/shared
    environment:
      - PROJECT=${PROJECT}
    command: >
      sh -c "
      if [ -n \"$${PROJECT}\" ]; then
        python /usr/src/app/$${PROJECT}/main_$${PROJECT}.py;
      else
        while :; do sleep 1000; done;
      fi
      "
    tty: true
